---
title: "S2208 MATH8050 Data Analysis - Section 001: Homework 6 Due on 10/19/22"
author: "Adithya Ravi, C09059838"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE, include=FALSE}
# load packages 

library(ggplot2)
library(stats)
library(ISLR2)
library(AR)

sessionInfo()
```

# Solutions

# Question1

## 1a 
```{r}
set.seed(100)

f<-function(x,a=2.7,b=6.3){
  return(x^(a-1)*((1-x)^(b-1)))
}

x=seq(0,1,10^-2)
C=max(f(x))
ggplot() +
  geom_line(aes(x,f(x)),color="red") + 
  geom_line(aes(x,1),color="green")
```

## 1b
```{r}
set.seed(123)

n=100
accept_1=NULL
accept.count=0
i=0

for(i in 1:n){
  X=runif(1,min=0,max=1)
  Y=runif(1,min=0,max=C)
  if(Y<=f(X)){
    accept.count=accept.count+1
    accept_1[accept.count]=X
  }
}

hist(accept_1,probability = TRUE)
```

```{r}
acceptance_ratio_1=length(accept_1)/n
acceptance_ratio_1
```

```{r}
n = 10^5
accept_2 = NULL
accept.count = 0
i=0

for(i in 1:n){
  X=runif(1, min=0, max=1)
  Y=runif(1, min=0, max=C)
  if(Y<=f(X)){
    accept.count=accept.count + 1
    accept_2[accept.count] = X
  }
}

hist(accept_2,probability = TRUE)
```

```{r}
acceptance_ratio_2=length(accept_2)/n
acceptance_ratio_2
```

## 1c
```{r}
plot(seq(0, 1, 10^-2), f(seq(0, 1, 10^-2)), type = "l", xlab = "",
     ylab = "Density", ylim = c(0, 2.75), col = "blue")

lines(seq(0, 1, 10^-2), dbeta(seq(0, 1, 10^-2), 2,6), col = "green")
```

```{r}
n = 10^2
accept_3 = NULL
accept.count = 0 
i = 0

for(i in 1:n){
  u = runif(1,
  min=0,
  max=1) 
  X=rbeta(1,2,6)
  if (u <= f(X)/C/dbeta(X,2,6) ){
    accept.count = accept.count+1
    accept_3[accept.count] = X 
  } 
}

length(accept_3)/100
```
```{r}
hist(accept_3,probability = TRUE)
```
```{r}

n = 10^5
accept_4 = NULL
accept.count = 0
i = 0

for(i in 1:n){
  u = runif(1,
  min=0,
  max=1) 
  X=rbeta(1,2,6)
  if (u <= f(X)/C/dbeta(X,2,6) ){
    accept.count = accept.count+1
    accept_4[accept.count] = X
  } 
}

length(accept_4)/10^5
```
```{r}
hist(accept_4,probability = TRUE)
```

## 1d
```{r}
par(mfrow = c(2,2))
hist(accept_1,probability = TRUE,xlab="Acceptance rate is 39 per",
     main="100 for uniform")

hist(accept_2,probability = TRUE,xlab="Acceptance rate is 37.5 per",
     main="10^5 for uniform")

hist(accept_3,probability = TRUE,xlab="Acceptance rate is 44 per",
     main="100 for beta")

hist(accept_4,probability = TRUE,xlab="Acceptance rate is 37.5 per",
     main="10^5 for beta")
```

## 1e
```{r}
set.seed(123)

n=10^5
stored<-rep(NA,n)
accept.count=0
previous=0.001

for(i in 1:n){
  present_value=runif(1,previous-0.001,previous+0.001)
  ratio=min(1,(f(present_value))/(f(previous)))
  accept=runif(1)<ratio
  stored[i]=ifelse(accept,present_value,previous)
  previous=stored[i]
}

plot(stored[1000:n],type='l')
```

```{r}
hist(stored[1000:n])
```

## 1f

```{r}
set.seed(123)

n=10^5
stored<-rep(NA,n)
accept.count=0
previous=0.01

for (i in 1:n){
  present_value=rnorm(1,previous,0.0034)
  ratio=min(1,(f(present_value))/(f(previous)))
  accept = runif(1) < ratio
  stored[i]<-ifelse(accept,present_value,previous)
  previous=stored[i]
}

plot(stored[2000:n],type='l')
```

```{r}
hist(stored[1000:n])
```

